"""add new field to tokens

Revision ID: 6149c4cd0c45
Revises: 01686cf4f3e7
Create Date: 2026-09-09 13:47:14.946636

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6149c4cd0c45"
down_revision: Union[str, None] = "01686cf4f3e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tokens", sa.Column("expires_at", sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tokens", "expires_at")
    # ### end Alembic commands ###
