"""unique for token

Revision ID: 6971bcc8ebcb
Revises: 6149c4cd0c45
Create Date: 2026-09-14 12:07:35.964666

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "6971bcc8ebcb"
down_revision: Union[str, None] = "6149c4cd0c45"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
